### ISSUE TITLE
Fallback in visual (block) mode only increments first line

### ISSUE THREAD

**Issue by kiryph** [bootleq/vim-cycle#11]
I have following minimal setup:

```
❯ tree ~/.vim
/Users/kiryph/.vim
├── pack
│   └── bootleq
│       └── start
│           └── vim-cycle
│               ├── CHANGES.md
│               ├── README.md
│               ├── autoload
│               │   ├── cycle
│               │   │   └── test.vim
│               │   └── cycle.vim
│               ├── doc
│               │   └── cycle.txt
│               ├── plugin
│               │   └── cycle.vim
│               └── test
│                   ├── example.txt
│                   └── group_operation.vim
└── vimrc

❯ cat vimrc
nmap  <C-A> <Plug>CycleNext
nmap  <C-X> <Plug>CyclePrev
vmap  <C-A> <Plug>CycleNext
vmap  <C-X> <Plug>CyclePrev
noremap  <Plug>CycleFallbackNext <C-A>
noremap  <Plug>CycleFallbackPrev <C-X>
```

Test file contains
```
1
1
1
1
```

I want to increment each line by 1 to get:
```
2
2
2
2
```

However, I get with `<C-V>3j` + `<C-A>`:
```
2
1
1
1
```
When I comment the content of vimrc, it works as expected.

Can vim-cycle be  improved or my configuration to support this?

**Comment by bootleq** [comment]
Hi, currently we still have limitation on multi-line block operation.

But it is reasonable that fallback `<C-A>` should respect visual lines.
I've pushed a new version **0.3.2** to improve a bit.

This version will work better, while I think fallback is still not perfectly mimic bulti-in one, at least, I found the dot (`.`) repeat can't take previous line count to replay.

Still suggest use another mapping for cycle, separated to `<C-A>`.
Thank you very much.

**Comment by kiryph** [comment]
Hi, thanks for your update!

I have pulled the new version into my minimal setup.

Unfortunately, I encountered an issue with it; probably related to your commit: https://github.com/bootleq/vim-cycle/commit/0b9c52360a8fd4980806c1a80db83e8e005ce149

If I now have a file with

```
1
1
1
2
```
and I want to decrease the last number to `1` with `G` and `<C-X>` the cursor jumps to the head of the file after the value has changed (no visual mode involved):
```
1 <CURSOR>
1
1
1
```
This is not the expected behavior.

For dot repeat, I think facilitating the plugin visualrepeat by Ingo Karkat (https://www.vim.org/scripts/script.php?script_id=3848) could be a possibility.

I have compared the fallback behaviour of ctrl-a/x to vim-speeddating by Tim Pope:
```
❯ tree ~/.vim
/Users/kiryph/.vim
└── pack
    └── tpope
        └── start
            ├── repeat
            │   ├── README.markdown
            │   └── autoload
            │       └── repeat.vim
            └── speeddating
                ├── README.markdown
                ├── autoload
                │   └── speeddating.vim
                ├── doc
                │   └── speeddating.txt
                └── plugin
                    └── speeddating.vim

9 directories, 6 files
```

Speeddating does not change the cursor after an increment in visual mode:
```
1
1
1
1
```
increment in visual mode and make sure cursor is at the bottom with `o`:
```
2
2
2
2 <CURSOR REMAINS>
```

However, I agree with your commit
```
Restore cursor to top after multi-line fallback

To mimic built-in behavior.
```

Other plugins with ctrl-a/x fallback functions for comparison are https://github.com/mjbrownie/swapit and https://github.com/Konfekt/vim-CtrlXA
- Konfekt/vim-CtrlXA overwrites `<C-X/A>` only for normal mode
- mjbrownie/swapit overwrites `<C-X/A>` for visual mode; however, it does not work for this situation: no fallback is triggered here.

**Comment by bootleq** [comment]
Hi, I've corrected the jump mistake first by https://github.com/bootleq/vim-cycle/commit/8aed8711.

Will do more study for the "repeat" issue.
Thanks for great help.

**Comment by kiryph** [comment]
Yes, your last commit fixed it. Thanks.

Have you ever thought about supporting incrementing cycle groups similarly in visual line or visual block mode?
E.g.
```
Monday
Tuesday
Wednesday
Thursday
Friday
```
are incremented in visual line mode to
```
Tuesday
Wednesday
Thursday
Friday
Saturday
```

BTW your documentation says about the default cycle_groups:
https://github.com/bootleq/vim-cycle/blob/2755df02cab82010d535ec28de80db567a3ef964/doc/cycle.txt#L335-L363

But if I am not mistaken it is actually:
https://github.com/bootleq/vim-cycle/blob/2755df02cab82010d535ec28de80db567a3ef964/plugin/cycle.vim#L25-L32

**Comment by bootleq** [comment]
Visual lines cycling could be two concepts:
1) batch operation on lines, like run single line cycle several times
2) allow a group item to run across lines like:
  `"Saturday"\n"Sunday"` <-> `"Weekend"`

Your example looks like the former and we could add some new function/mapping for it.
While I'd like to use `:substitute` or others since cycle items were ususally very simple words.

For the "default" issue, the longer list in doc is a full example to set user-customized default, but not the internal plugin default.
Hope it won't confuse too much, we do have multi layers of defaults.

Anyway I will push a new version later, if have other idea, welcome to open new issues, thank you.

**Comment by kiryph** [comment]
> Visual lines cycling could be two concepts:

Agreed.

Another feature (😃) could be to support something in the spirit of [`v_g_CTRL-A`](http://vimhelp.appspot.com/change.txt.html#v_g_CTRL-A).

> Hope it won't confuse too much, we do have multi layers of defaults.

I actually think that it is slightly confusing. I would change

```
Default global groups:
```
to
```
Global groups:
```

It is also not clear why ruby, rails, css, html suggestions are not in the filetype specific section. For instance, `[none, block]` does not seem to be a good candidate for a global definition. The same for `['em', 'strong', 'small']`.

Are you sure you need several layers of defaults? I think this is not necessary.

**Comment by bootleq** [comment]
I've changed the wording `Default global groups` follow your suggesion, thanks.

The ruby, html groups were added to "global" since I personally do it, I often write those words in usual text files.
There is a "filetype specific" section in doc, guess it provide enough hint to user.

**Comment by kiryph** [comment]
Thanks for your updates. I hope new users of your plugin find them helpful.
