### ISSUE TITLE
It doesn't match upper string when match_word is true

### ISSUE THREAD

**Issue by tenfyzhong** [bootleq/vim-cycle#8]
configuration: 
```viml
let g:cycle_default_groups = [[['true', 'false'], 'match_word']]
```
code:
```python
if True:
    pass
```
The `True` doesn't switch to `False` when I call `<Plug>CycleNext`.

**Comment by bootleq** [comment]
Hi, sorry I am not sure what the problem is.
With configuration you provided, I can cycle `True` to `False` in normal mode, with cursor put on `T` or `r`.
Would you help to describe a bit more? Thanks.

**Comment by bootleq** [comment]
I'm closing this due to unable to reproduce.
